### ISSUE TITLE
Issues in Training Step 1

### ISSUE THREAD

**Issue by aflah02** [machelreid/lewis#3]
Just for future users there is a typo in the command 
`bash preprocess-roberta-classifer.sh path/to/data <prefix> <domain-1-suffix> <domain-2-suffix>`
It should be 
`bash preprocess-roberta-classifier.sh path/to/data <prefix> <domain-1-suffix> <domain-2-suffix>`
There is a missing `i` in the word classifier
Apart from that I am a bit confused about how to run this. Where exactly am I expected to run this command? If I run it in `~/lewis/roberta-classifier` where the `.sh` file is located I'm prompted with many errors - 

`(lewis) aflah20082@LS83:~/lewis/roberta-classifier$ bash preprocess-roberta-classifier.sh downloads eval domain-1-Hate domain-2-LessHate
preprocess-roberta-classifier.sh: line 14: downloads/eval/train.txt: No such file or directory
2021-12-20 12:59:34 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aflah20082/fairseq/examples/roberta/multiprocessing_bpe_encoder.py", line 130, in <module>
    main()
  File "/home/aflah20082/fairseq/examples/roberta/multiprocessing_bpe_encoder.py", line 64, in main
    for input in args.inputs
  File "/home/aflah20082/fairseq/examples/roberta/multiprocessing_bpe_encoder.py", line 64, in <listcomp>
    for input in args.inputs
FileNotFoundError: [Errno 2] No such file or directory: 'downloads/eval/train.txt'
preprocess-roberta-classifier.sh: line 14: downloads/eval/valid.txt: No such file or directory
2021-12-20 12:59:35 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
Traceback (most recent call last):
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aflah20082/fairseq/examples/roberta/multiprocessing_bpe_encoder.py", line 130, in <module>
    main()
  File "/home/aflah20082/fairseq/examples/roberta/multiprocessing_bpe_encoder.py", line 64, in main
    for input in args.inputs
  File "/home/aflah20082/fairseq/examples/roberta/multiprocessing_bpe_encoder.py", line 64, in <listcomp>
    for input in args.inputs
FileNotFoundError: [Errno 2] No such file or directory: 'downloads/eval/valid.txt'
2021-12-20 12:59:37 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2021-12-20 12:59:37 | INFO | fairseq_cli.preprocess | Namespace(align_suffix=None, alignfile=None, all_gather_list_size=16384, amp=False, amp_batch_retries=2, amp_init_scale=128, amp_scale_window=None, azureml_logging=False, bf16=False, bpe=None, cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='downloads/roberta-classifier/eval/data-bin/input0', dict_only=False, empty_cache_freq=0, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_file=None, log_format=None, log_interval=100, lr_scheduler='fixed', memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, model_parallel_size=1, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, on_cpu_convert_precision=False, only_source=True, optimizer=None, padding_factor=8, plasma_path='/tmp/plasma', profile=False, quantization_config_path=None, reset_logging=False, scoring='bleu', seed=1, simul_type=None, source_lang=None, srcdict='downloads/gpt2_bpe/dict.txt', suppress_crashes=False, target_lang=None, task='translation', tensorboard_logdir=None, testpref=None, tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer=None, tpu=False, trainpref='downloads/roberta-classifier/eval/train.bpe', use_plasma_view=False, user_dir=None, validpref='downloads/roberta-classifier/eval/valid.bpe', wandb_project=None, workers=60)
Traceback (most recent call last):
  File "/home/aflah20082/yes/envs/lewis/bin/fairseq-preprocess", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')())
  File "/home/aflah20082/fairseq/fairseq_cli/preprocess.py", line 407, in cli_main
    main(args)
  File "/home/aflah20082/fairseq/fairseq_cli/preprocess.py", line 102, in main
    src_dict = task.load_dictionary(args.srcdict)
  File "/home/aflah20082/fairseq/fairseq/tasks/fairseq_task.py", line 94, in load_dictionary
    return Dictionary.load(filename)
  File "/home/aflah20082/fairseq/fairseq/data/dictionary.py", line 226, in load
    d.add_from_file(f)
  File "/home/aflah20082/fairseq/fairseq/data/dictionary.py", line 239, in add_from_file
    raise fnfe
  File "/home/aflah20082/fairseq/fairseq/data/dictionary.py", line 236, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'downloads/gpt2_bpe/dict.txt'
wc: downloads/eval/domain-1-Hate/train.txt: No such file or directory
seq: missing operand
Try 'seq --help' for more information.
wc: /domain-1-Hate/valid.txt: No such file or directory
seq: missing operand
Try 'seq --help' for more information.
wc: downloads/eval/domain-2-LessHate/train.txt: No such file or directory
seq: missing operand
Try 'seq --help' for more information.
wc: downloads/eval/domain-2-LessHate/valid.txt: No such file or directory
seq: missing operand
Try 'seq --help' for more information.
2021-12-20 12:59:38 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2021-12-20 12:59:38 | INFO | fairseq_cli.preprocess | Namespace(align_suffix=None, alignfile=None, all_gather_list_size=16384, amp=False, amp_batch_retries=2, amp_init_scale=128, amp_scale_window=None, azureml_logging=False, bf16=False, bpe=None, cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='downloads/roberta-classifier/eval/data-bin/label', dict_only=False, empty_cache_freq=0, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_file=None, log_format=None, log_interval=100, lr_scheduler='fixed', memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, model_parallel_size=1, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, on_cpu_convert_precision=False, only_source=True, optimizer=None, padding_factor=8, plasma_path='/tmp/plasma', profile=False, quantization_config_path=None, reset_logging=False, scoring='bleu', seed=1, simul_type=None, source_lang=None, srcdict=None, suppress_crashes=False, target_lang=None, task='translation', tensorboard_logdir=None, testpref=None, tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer=None, tpu=False, trainpref='downloads/roberta-classifier/eval/train.label', use_plasma_view=False, user_dir=None, validpref='downloads/roberta-classifier/eval/valid.label', wandb_project=None, workers=60)
Traceback (most recent call last):
  File "/home/aflah20082/yes/envs/lewis/bin/fairseq-preprocess", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')())
  File "/home/aflah20082/fairseq/fairseq_cli/preprocess.py", line 407, in cli_main
    main(args)
  File "/home/aflah20082/fairseq/fairseq_cli/preprocess.py", line 107, in main
    src_dict = build_dictionary([train_path(args.source_lang)], src=True)
  File "/home/aflah20082/fairseq/fairseq_cli/preprocess.py", line 72, in build_dictionary
    padding_factor=args.padding_factor,
  File "/home/aflah20082/fairseq/fairseq/tasks/fairseq_task.py", line 115, in build_dictionary
    filename, d, tokenizer.tokenize_line, workers
  File "/home/aflah20082/fairseq/fairseq/data/dictionary.py", line 354, in add_file_to_dictionary
    offsets = find_offsets(local_file, num_workers)
  File "/home/aflah20082/fairseq/fairseq/file_chunker_utils.py", line 25, in find_offsets
    with open(filename, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'downloads/roberta-classifier/eval/train.label'
Data in downloads/eval has finished preprocessing, and the final output is in downloads/roberta-classifier/eval/data-bin`

I've named `path/to/data` as `downloads` and this is the remaining folder setup -

<img width="183" alt="image" src="https://user-images.githubusercontent.com/72096386/146729671-cd306927-be00-48cf-a9e0-5534ce7cb4d2.png">

**Comment by machelreid** [comment]
Oh it look like there are some file not found errors because of a typo: what if you try to replace "eval" in your command with "dataset-eval"?

**Comment by aflah02** [comment]
Hey I tried with dataset-eval as well the error persists, I'll close this issue and explain the problem in the other one as they are the same
