### ISSUE TITLE
Dataset Size Mismatch Issue Being Caused

### ISSUE THREAD

**Issue by aflah02** [machelreid/lewis#7]
Hey
I've been trying to replicate the code using a custom dataset and it worked well for the first few steps then in one of the steps it throws an error from the referenced line (https://github.com/pytorch/fairseq/blob/98ebe4f1ada75d006717d84f9d603519d8ff5579/fairseq/data/nested_dictionary_dataset.py#L63) saying mismatch in sizes and when I try to print out I see the sizes are different but I can't figure out what can cause this as the datasets have same length on manual inspection.
Also I tried to see what happens if I move the line https://github.com/pytorch/fairseq/blob/98ebe4f1ada75d006717d84f9d603519d8ff5579/fairseq/data/nested_dictionary_dataset.py#L53 inside the for loop the error vanishes from there but reappears at https://github.com/pytorch/fairseq/blob/98ebe4f1ada75d006717d84f9d603519d8ff5579/fairseq/data/sort_dataset.py#L18 and on printing I can see the lengths causing the assertion error are the same as the lengths causing the assertion error prior to changing the code in nested_dictionary_dataset.py
Also the assertion error happens presumably with the validation dataset as one of the values is 2x the size of the validation dataset while the other is the same size if that helps
Any clues I can follow?

**Comment by aflah02** [comment]
The precise error is this - 

`(lewis) aflah20082@LS83:~/lewis/roberta-classifier$ bash train-roberta-classifier.sh /home/aflah20082/lewis/downloads dataset-eval
2021-12-23 01:27:23 | INFO | fairseq_cli.train | Namespace(activation_dropout=0.0, activation_fn='gelu', adam_betas='(0.9, 0.98)', adam_eps=1e-06, add_prev_output_tokens=False, all_gather_list_size=16384, arch='roberta_base', attention_dropout=0.1, batch_size=64, batch_size_valid=64, best_checkpoint_metric='accuracy', bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='', classification_head_name='classification_head', clip_norm=0.0, cpu=False, criterion='sentence_prediction', curriculum=0, data='/home/aflah20082/lewis/downloads/roberta-classifier/dataset-eval/data-bin', data_buffer_size=10, dataset_impl=None, ddp_backend='c10d', device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_num_procs=1, distributed_port=-1, distributed_rank=0, distributed_world_size=1, distributed_wrapper='DDP', dropout=0.1, empty_cache_freq=0, encoder_attention_heads=12, encoder_embed_dim=768, encoder_ffn_embed_dim=3072, encoder_layerdrop=0, encoder_layers=12, encoder_layers_to_keep=None, end_learning_rate=0.0, fast_stat_sync=False, find_unused_parameters=True, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=True, fp16_init_scale=4, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=128, gen_subset='test', init_token=0, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_last_epochs=-1, localsgd_frequency=3, log_format=None, log_interval=100, lr=[1e-05], lr_scheduler='polynomial_decay', max_epoch=10, max_positions=512, max_tokens=8192, max_tokens_valid=8192, max_update=0, maximize_best_checkpoint_metric=True, memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1.0, model_parallel_size=1, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_seed_provided=False, no_shuffle=False, nprocs_per_node=1, num_classes=2, num_shards=1, num_workers=1, optimizer='adam', optimizer_overrides='{}', patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, pooler_activation_fn='tanh', pooler_dropout=0.0, power=1.0, profile=False, quant_noise_pq=0, quant_noise_pq_block_size=8, quant_noise_scalar=0, quantization_config_path=None, regression_target=False, required_batch_size_multiple=1, required_seq_len_multiple=1, reset_dataloader=True, reset_lr_scheduler=False, reset_meters=True, reset_optimizer=True, restore_file='/home/aflah20082/lewis/downloads/roberta.base/model.pt', save_dir='/home/aflah20082/lewis/downloads/roberta-classifier/dataset-eval/checkpoints', save_interval=1, save_interval_updates=0, scoring='bleu', seed=1, sentence_avg=False, separator_token=2, shard_id=0, shorten_data_split_list='', shorten_method='truncate', skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, spectral_norm_classification_head=False, stop_time_hours=0, task='sentence_prediction', tensorboard_logdir=None, threshold_loss_scale=1.0, tokenizer=None, total_num_update=10000, tpu=False, train_subset='train', update_freq=[1], use_bmuf=False, use_old_adam=False, user_dir=None, valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, warmup_updates=469, weight_decay=0.1, zero_sharding='none')
2021-12-23 01:27:23 | INFO | fairseq.tasks.sentence_prediction | [input] dictionary: 50265 types
2021-12-23 01:27:23 | INFO | fairseq.tasks.sentence_prediction | [label] dictionary: 9 types

ARGS --- valid

2021-12-23 01:27:23 | INFO | fairseq.data.data_utils | loaded 908 examples from: /home/aflah20082/lewis/downloads/roberta-classifier/dataset-eval/data-bin/input0/valid
2021-12-23 01:27:23 | INFO | fairseq.data.data_utils | loaded 454 examples from: /home/aflah20082/lewis/downloads/roberta-classifier/dataset-eval/data-bin/label/valid
Traceback (most recent call last):
  File "/home/aflah20082/.local/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/home/aflah20082/.local/lib/python3.6/site-packages/fairseq_cli/train.py", line 355, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/aflah20082/.local/lib/python3.6/site-packages/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/home/aflah20082/.local/lib/python3.6/site-packages/fairseq_cli/train.py", line 68, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "/home/aflah20082/.local/lib/python3.6/site-packages/fairseq/tasks/sentence_prediction.py", line 238, in load_dataset
    sizes=[src_tokens.sizes],
  File "/home/aflah20082/.local/lib/python3.6/site-packages/fairseq/data/nested_dictionary_dataset.py", line 70, in __init__
    assert len(v) == len(first), "dataset lengths must match"
AssertionError: dataset lengths must match
train-roberta-classifier.sh: line 57: --tensorboard-logdir: command not found`

The ARGS --- valid printed in between is due to a print statement I've added

**Comment by aflah02** [comment]
This is solved by the PR

**Comment by xiaowen3679** [comment]
Hello! I encountered a problem similar to yours when running the "train-roberta-classifier.sh" file.
I have seen your process in PR and modified two files "preprocess-bart-mt.sh" and "preprocess-roberta-classifier.sh".
However, how should "train-roberta-classifier.sh" be modified?

**Comment by aflah02** [comment]
@xiaowen3679 Really sorry it's been a long time and I don't remember any modifications I might've done apart from the ones in the PR. I believe I had added all additions in the PR, what issue are you facing with "train-roberta-classifier.sh"? Maybe I remember something by seeing the error

**Comment by li-jing-wen** [comment]
> @xiaowen3679 Really sorry it's been a long time and I don't remember any modifications I might've done apart from the ones in the PR. I believe I had added all additions in the PR, what issue are you facing with "train-roberta-classifier.sh"? Maybe I remember something by seeing the error

Thank you very much for your reply！ 
I have found the problem and solved it successfully.
